### ISSUE TITLE
关于代码读取数据的疑问

### ISSUE THREAD

**Issue by PershingY** [benzenemo/TightlyCoupledINSGNSS#11]
您好，我最近在学习组合导航方面的知识，用matlab2022a运行您的代码时遇到了一个报错：
load('..\TCdata\GNSSObsForCouple\2018\165\小车\GNSSRes2018-06-28-21-16')报错为：最初保存为 dataset 的变量 'GNSSRes' 无法实例化为对象，将以 uint32 形式读取。 
我查询相关的报错怀疑是这个数据在打包是缺少相应的引用，请问是否是缺少了部分的数据呢？

**Comment by benzenemo** [comment]
抱歉我确实没遇到过这个问题，其它人也没有给我反馈过类似的问题发自我的荣耀手机
