### ISSUE TITLE
请问GNSSObs里的伪距率是怎么算出来的

### ISSUE THREAD

**Issue by kakusang2020** [benzenemo/TightlyCoupledINSGNSS#2]
请问GNSSObs里的伪距率是怎么算出来的

**Comment by benzenemo** [comment]
@kakusang2020 用GNSS的多普勒观测值计算的，伪距率 = - 多普勒*光速/频率

**Comment by kakusang2020** [comment]
> @kakusang2020 用GNSS的多普勒观测值计算的，伪距率 = - 多普勒*光速/频率

多谢，看您的代码很久了，现在用自己的数据试试。RecClockRateAll是300多，还在找问题。😁
