### ISSUE TITLE
关于数据集中IMU的疑惑

### ISSUE THREAD

**Issue by kakusang2020** [benzenemo/TightlyCoupledINSGNSS#4]
您好，我看您的IMU坐标系写的是前右下，加速度单位是(m*s-2)。

**Comment by kakusang2020** [comment]
但是加速度z是负值，难道安装的时候是朝下的吗？
还有就是单位是米每二次方秒吗？
我看z的加速度基本不等于9.8，那个值 和 在算IMU速度的时候移除的G矢量数值差不多，
请问是对IMU数据做了旋转吗？
这个问题可能比较幼稚。。。希望大佬有空回答一下，👍

**Comment by benzenemo** [comment]
@kakusang2020 看到你把这个问题关闭了 是不是已经查到了问题的答案。
加速度计测量的是比力 （specific force）

**Comment by kakusang2020** [comment]
> @kakusang2020 看到你把这个问题关闭了 是不是已经查到了问题的答案。
> 加速度计测量的是比力 （specific force）

多谢回复，我查了一下概念：
单位质量上作用的非引力外力，称之为比力。
算是基本想明白了吧，哈哈哈😀
