### ISSUE TITLE
关于抗差滤波的推导

### ISSUE THREAD

**Issue by kakusang2020** [benzenemo/TightlyCoupledINSGNSS#5]
您好，看您的代码，抗差滤波那里用𝑍./√(diag(𝐻 ∗𝑃 ∗𝐻^′+𝑅))来算新息标准差，这个怎么推导出来的呢？
看M-LS也是类似的疑惑，z和R + H * P * H’有什么数学联系呢？
我目前理解的是R + H * P * H’理解为新息协方差，开根号是标准差，其他的就不清楚了。。。
我看注释中提到的参考书，只有三段式那块对应上了，其他的一头雾水，大佬能否解答一下。😀

**Comment by benzenemo** [comment]
@kakusang2020  

1. 你说的是函数IAE_KF_Epoch第166行StdInno的公式吧？StdInno（Standardized Innovation）不是新息的标准差，是标准化新息，计算公式见文献
Li T, Zhang H, Gao Z, et al. High-accuracy positioning in urban environments using singlefrequency multi-GNSS RTK/MEMS-IMU integration[J]. Remote Sensing, 2018, 10(2):
205.中有，见公式（21）。

2.函数MLS_KF_Epoch中相应的StdResi也是指标准化残差，公式参考了文献
程义军, 孙海燕, 程海斌. 抗差卡尔曼滤波及其在动态水准网平差中的应用[J]. 测
绘工程, 2004, 13(04):55-57+71.
陶本藻. 卡尔曼滤波模型误差的识别[J]. 大地测量与地球动力学, 1999, 19(4):15-20.

**Comment by kakusang2020** [comment]
多谢，硕士毕业论文全依仗大佬答疑指点了😀
