### ISSUE TITLE
关于ZARU在卡尔曼滤波中的使用

### ISSUE THREAD

**Issue by kakusang2020** [benzenemo/TightlyCoupledINSGNSS#6]
您好，看您的代码中零速检测是当速度为0时，陀螺仪z轴的输出等于自身的误差，为什么不把另外两个轴也当作量测值呢？
我用自己的数据集试了一下，陀螺仪三个轴都做ZARU效果好像会更好点？

**Comment by benzenemo** [comment]
可以把ZARU用到三轴上。
我当时小车采集的数据振动比较大，振动导致俯仰与横滚轴的ZARU观测噪声大于两个轴状态的误差，所以按参考书15.3节的建议，只在偏航角处理时用了ZARU。

**Comment by kakusang2020** [comment]
好的，谢谢
